all:
	g++ -o dpsws2016-analyze -g -O0 -std=c++11 -I../../include/ dpsws2016-analyze.cc -L../../ -lpgen2
	g++ -o dpsws2016-generate -g -O0 -std=c++11 -I../../include/ dpsws2016-generate.cc -L../../ -lpgen2

clean:
	rm -rf a.out dpsws2016-analyze dpsws2016-create

