

PROTOCOL_SRC = \
	eth.cc \
	arp.cc \
	ip.cc \
	icmp.cc \
	tcp.cc \
	udp.cc \
	dns.cc 

	# ardrone.cc 
	# http.cc 
	# dhcp.cc 

PROTOCOL_HDR = protocols.h \
	eth.h \
	arp.h \
	ip.h \
	icmp.h \
	tcp.h \
	udp.h \
	dns.h 

	#ardrone.h 
	#http.h 
	#dhcp.h 

